CREATE TABLE public.delivery (
	delivery_deadline date NULL,
	quantity_packages int4 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city varchar(255) NULL,
	complement varchar(255) NULL,
	cpf_client varchar(255) NULL,
	district varchar(255) NULL,
	name_client varchar(255) NULL,
	"number" varchar(255) NULL,
	street varchar(255) NULL,
	uf varchar(255) NULL,
	zip_code varchar(255) NULL,
	CONSTRAINT delivery_pkey PRIMARY KEY (id)
);